[package]
name = "crawl"
version = "0.1.0"
authors = ["Miguel Young de la Sota <mcyoung@mit.edu>"]
edition = "2018"

[dependencies]
crossterm = "0.19.0"
legion = "0.3.1"
num = "0.3.1"
palette = "0.5.0"
rand = "0.8.2"